### ISSUE TITLE
Błąd

### ISSUE THREAD

**Issue by SiopeK** [Kichiyaki/margonem-mini-bot#1]
level=fatal msg="Cannot unmarshal config file content into config struct: invalid character ']' looking for beginning of value"

Id wpisałem dobre, na kilku postaciach próbowałem i nie działa.

**Comment by Kichiyaki** [comment]
Twój config ma gdzieś ] za dużo. Podeślij go tutaj, zmieniając username, password i postacie na jakieś losowe dane to Ci go poprawie.

**Comment by SiopeK** [comment]
{
  "accounts": [
    {
      "username": "login",
      "password": "haslo",
      "proxy": "",
      "characters": [
        {
          "id": "zorza#ID",
          "map_id": "2829"
        },
      ]
    }
  ],
  "debug": false
}

**Comment by Kichiyaki** [comment]
```
{
"id": "zorza#ID",
"map_id": "2829"
},
```
Przecinek znajdujący się na końcu obiektu wszystko psuje.


Tak to powinno wyglądać:
```
{
  "accounts": [
    {
      "username": "login",
      "password": "haslo",
      "proxy": "",
      "characters": [
        {
          "id": "zorza#ID",
          "map_id": "2829"
        }
      ]
    }
  ],
  "debug": false
}

```

**Comment by SiopeK** [comment]
dzięki wielkie
