### ISSUE TITLE
Problem z botem.

### ISSUE THREAD

**Issue by ziomek134** [Kichiyaki/margonem-mini-bot#2]
Po skonfigurowaniu bota wyskakuje mi coś takiego w logach:

`time="2020-05-07T13:24:52+02:00" level=info msg="Running cron job" charid=926157 mapid=2795
time="2020-05-07T13:24:53+02:00" level=info msg="Finished cron job" charid=926157 err="findCharacterByID: Cannot find a character with id 926157" mapid=2795
time="2020-05-07T13:24:53+02:00" level=info msg="Running cron job" charid=926197 mapid=2676
time="2020-05-07T13:24:53+02:00" level=info msg="Finished cron job" charid=926197 err="findCharacterByID: Cannot find a character with id 926197" mapid=2676

Może źle go skonfigurowałem. Nie mam pojęcia o co chodzi. Mógłbyś pomóc?`

**Comment by Kichiyaki** [comment]
Wyślij mi swój profil i nick postaci + świat, który Cię interesuję na discordzie Kichiyaki#2064 lub tutaj (nie radziłbym, bo administracja będzie miała konto podane na talerzu).

**Comment by Kichiyaki** [comment]
I charid powinno wyglądać tak: świat#id (np. zorza#926157, gefion#926157)

**Comment by ziomek134** [comment]
Dzięki stary za pomoc. Błędem było pisanie nazwy świata z dużej litery, bo próbowałem na kilka sposobów (pisałem np. Jaruna#926157, Gefion etc.) Zmieniłem na małą literę i zaczęło działać normalnie. 

Jak będę miał jakiś problem, to napisze do ciebie na discorda. Nie chcę ci czasu zajmować z błahostkami. Dzięki za bota.
